kind: v3
name: crabtrap
resources:
  cpu: 512
  memory: 1024
environments:
  MPL_CONFIG_ENV: stg
  awslogs-group: /stg/apse1/crabtrap
  awslogs-stream-prefix: ecs
secrets:
  DATABASE_URL: /stg/apse1/crabtrap/database/url
